### ISSUE TITLE
Gjør det mulig å vise popup-vinduer

### ISSUE THREAD

**Issue by SteinarSi** [inf112-v21/Trivial-Solution#20]
Som selve spillet ønsker jeg å kunne eksplisitt gi beskjeder til spilleren på en noenlunde fin måte, så spilleren får med seg beskjeden.

Akseptansekrav:
- Spillet kan åpne et popupvindu med en valgfri beskjed.

Selve oppgaven: implementer `.showPopup(String message)` i GUI.

**Comment by sandersig** [comment]
Fant ut det ikke var noen måte å vise popup-vinduer i OpenGL eller Lwjgl3, så bruker metoden "JOptionPane.showMessageDialog" isteden.
