### ISSUE TITLE
Lage en klasse for brettet

### ISSUE THREAD

**Issue by sandersig** [inf112-v21/Trivial-Solution#3]
Som spiller vil jeg kunne se et spillebrett, så jeg enklere kan visualisere hva som skjer.
Som spiller vil jeg kunne se hvor mine og andre spillere sine brikker skal stå, slik at jeg lettere kan planlegge neste trekk.
Som spiller vil jeg kunne flytte brikken min på en intuitiv måte.

Finne ut hvordan et brett skal representeres, hvilke layers det skal bestå av, hvilke metoder klassen skal ha.

**Comment by SteinarSi** [comment]
Her var vi for upresise med akseptansekravene. Det skulle heller vært noe som 'lag en enkel implementasjon av Board som kan huske hvilke ruter som står hvor. De skal bruke objektversjonen av hver rute'. Lukker denne nå.
