### ISSUE TITLE
.dispose()

### ISSUE THREAD

**Issue by SteinarSi** [inf112-v21/Trivial-Solution#96]
Hver gang vi lukker programmet får vi `AL lib: (EE) alc_cleanup: 1 device not closed` i terminalen. Jeg tror det er fordi at Libgdx-vinduer skal lukkes på en speisell måte eller noe.

Når vi lukker programmet etter det har startet en server lukkes ikke programmet helt, serveren fortsetter å gå helt til man terminerer det i IntelliJ. Antagelig skal servere også lukkes på en spesiell måte.

Oppgave: finn ut av hvordan vi kan lukke hele programmet på en god måte, slik at både alt+f4 og å krysse ut vinduet lukker alt sammen uten feilmeldinger.

**Comment by sandersig** [comment]
Jeg tok å endret System.exit(0) til Gdx.app.exit(). Så denne skal være fikset nå.
